---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName:
      hostpath
  hostPath:
    path: /Users/syednadeem/Documents/workspace_dockerK8s_traning/project_sessions/session-7/deployment_yamls/secure_dbase_deployment/mount  # Update this path based on your environment
