apiVersion: v1
kind: Pod
metadata:
  name: ui-pod
  labels:
    app: UI
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: ui-only
    operator: Exists
    effect: NoSchedule
