version: '3.2'
networks:
  mynetwork:
    driver: bridge 
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    ports:
      - "9002:9000"
    image: myapp:baseImage
    networks:
      - mynetwork
  multistaged:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9000"
    image: myapp:productionImage
    networks:
      - mynetwork
  multistaged-replica:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    image: myapp:productionImage
    networks:
      - mynetwork
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    networks:
      - mynetwork
